theme: jekyll-theme-minimal
logo: /_logos/r_dna_neuron.png
title: Bioinformatics 
baseurl: "/BIMM143" 
# url: "https://neurabyte-ucsd-its.github.io/BIMM143/"
url: "neurabyte-ucsd-its.github.io/BIMM143/"

include:
  - _logos
  - _layout
